In [ ]:
# !pip install fasttext
# !pip install numpy==1.23.5
import pandas as pd
import re
import fasttext
from sklearn.model_selection import train_test_split

In [ ]:
df= pd.read_csv("21) ecommerce_data.csv", names=["category", "description"], header=None)
print(df.category.value_counts())
df.category.replace("Clothing & Accessories", "Clothing_Accessories", inplace=True)
df.dropna(inplace=True)
print(df.shape)
df.head(3)

category
Household                 19313
Books                     11820
Electronics               10621
Clothing & Accessories     8671
Name: count, dtype: int64
(50424, 2)

<ipython-input-3-752601285905>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.category.replace("Clothing & Accessories", "Clothing_Accessories", inplace=True)

    category                                        description
0  Household  Paper Plane Design Framed Wall Hanging Motivat...
1  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2  Household  SAF 'UV Textured Modern Art Print Framed' Pain...

In [ ]:
df["traindata"] = "__label__" + df["category"] + " " + df["description"]
def preprocess(text):
    text = re.sub(r'[^\w\s\']',' ', text)
    text = re.sub(' +', ' ', text)
    return text.strip().lower()
df["traindata"] = df["traindata"].map(preprocess)
train, test = train_test_split(df, test_size=0.2)
train.to_csv("7) ecommerce_train", columns=["traindata"], index=False, header=False)
test.to_csv("8) ecommerce_test", columns=["traindata"], index=False, header=False)
df

,category,description,traindata
0,Household,Paper Plane Design Framed Wall Hanging Motivat...,__label__household paper plane design framed w...
1,Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",__label__household saf 'floral' framed paintin...
2,Household,SAF 'UV Textured Modern Art Print Framed' Pain...,__label__household saf 'uv textured modern art...
3,Household,"SAF Flower Print Framed Painting (Synthetic, 1...",__label__household saf flower print framed pai...
4,Household,Incredible Gifts India Wooden Happy Birthday U...,__label__household incredible gifts india wood...
...,...,...,...
50420,Electronics,Strontium MicroSD Class 10 8GB Memory Card (Bl...,__label__electronics strontium microsd class 1...
50421,Electronics,CrossBeats Wave Waterproof Bluetooth Wireless ...,__label__electronics crossbeats wave waterproo...
50422,Electronics,Karbonn Titanium Wind W4 (White) Karbonn Titan...,__label__electronics karbonn titanium wind w4 ...
50423,Electronics,"Samsung Guru FM Plus (SM-B110E/D, Black) Colou...",__label__electronics samsung guru fm plus sm b...
50424,Electronics,Micromax Canvas Win W121 (White),__label__electronics micromax canvas win w121 ...

In [ ]:
model = fasttext.train_supervised(input="7) ecommerce_train")
model.test("8) ecommerce_test")

(10084, 0.9656882189607299, 0.9656882189607299)

In [ ]:
model.predict("motog34 snapdragon 695 5G 8gb ram 50mp quadpixel camera.")

(('__label__electronics',), array([0.82916307]))

In [ ]:
model.predict("Sun Tzu: Art of War")

(('__label__books',), array([1.00001001]))

In [ ]:
model.get_nearest_neighbors("charger")

[(0.9989867210388184, 'whiter'),
 (0.9989839196205139, 'halfway'),
 (0.9989821910858154, 'bp150'),
 (0.9989768266677856, 'c2500'),
 (0.9989765882492065, 'memeorable'),
 (0.9989699721336365, 'concentrate'),
 (0.998965322971344, 'transformer'),
 (0.9989616274833679, 'capsules'),
 (0.9989599585533142, 'flushing'),
 (0.9989579916000366, 'wmm')]

In [ ]:
model.get_analogies("samsung","phone","laptop")

[(0.9979010820388794, 'isolated'),
 (0.9976845979690552, '24h'),
 (0.9975510239601135, 'noticed'),
 (0.9975250363349915, '250x'),
 (0.9973129034042358, 'shatter'),
 (0.9970483779907227, 'disappointed'),
 (0.9970143437385559, 'acoustic'),
 (0.9968999028205872, 'blemishes'),
 (0.9960519671440125, 'ac110'),
 (0.9942753314971924, '440')]